services:
  ingest:
    build:
      context: ../../
      dockerfile: apps/ingest-workers/Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - ${INGEST_ENV_FILE:-.env.ingest.local}
    stop_signal: SIGTERM
    stop_grace_period: 30s
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    networks:
      - issue-to-pr-network

