"use client"

import { Loader2, Mic } from "lucide-react"
import { useCallback, useEffect, useRef, useState } from "react"

import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { getGithubUser } from "@/lib/github/users"
import { toast } from "@/lib/hooks/use-toast"
import { createTask } from "@/lib/neo4j/services/task"
import { IssueTitleResponseSchema } from "@/lib/types/api/schemas"
import { RepoFullName } from "@/lib/types/github"

interface Props {
  repoFullName: RepoFullName
}

export default function NewTaskInput({ repoFullName }: Props) {
  const [description, setDescription] = useState("")
  const [loading, setLoading] = useState(false)
  const [generatingTitle, setGeneratingTitle] = useState(false)

  // Recording related state
  const [isRecording, setIsRecording] = useState(false)
  const [isTranscribing, setIsTranscribing] = useState(false)
  const [mediaRecorder, setMediaRecorder] = useState<MediaRecorder | null>(null)
  const audioChunks = useRef<Blob[]>([])

  // Cleanup recorder on unmount
  useEffect(() => {
    return () => {
      mediaRecorder?.stream.getTracks().forEach((t) => t.stop())
    }
  }, [mediaRecorder])

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()

    if (!description.trim()) {
      toast({
        title: "Description required",
        description: "Please enter a description for your task.",
        variant: "destructive",
      })
      return
    }

    // Title will be auto-generated by an agent
    let taskTitle = ""
    try {
      setGeneratingTitle(true)
      const res = await fetch("/api/playground/issue-title", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ description }),
      })
      const data = await res.json()
      const parsedData = IssueTitleResponseSchema.safeParse(data)

      if (!parsedData.success) {
        throw new Error(parsedData.error.message)
      }

      taskTitle = parsedData.data.title.trim()
      if (!taskTitle) throw new Error("Received empty title from agent")
    } catch (err: unknown) {
      toast({
        title: "Error generating title",
        description: String(err),
        variant: "destructive",
      })
      setGeneratingTitle(false)
      return
    } finally {
      setGeneratingTitle(false)
    }

    setLoading(true)
    try {
      const user = await getGithubUser()
      if (!user) {
        throw new Error("User not found")
      }

      await createTask({
        repoFullName,
        title: taskTitle,
        body: description,
        createdBy: user.login,
      })

      toast({
        title: "Task created",
        description: `Created: ${taskTitle}`,
        variant: "default",
      })
      setDescription("")
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      toast({
        title: "Error creating task",
        description: message,
        variant: "destructive",
      })
    } finally {
      setLoading(false)
    }
  }

  const isSubmitting = loading || generatingTitle

  const startRecording = async () => {
    if (!navigator.mediaDevices?.getUserMedia) {
      toast({
        description: "Your browser does not support audio recording.",
        variant: "destructive",
      })
      return
    }

    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true })
      const recorder = new MediaRecorder(stream)
      recorder.ondataavailable = (e) => {
        if (e.data.size > 0) audioChunks.current.push(e.data)
      }
      recorder.onstop = handleRecordingStop
      recorder.start()
      setMediaRecorder(recorder)
      setIsRecording(true)
    } catch {
      toast({
        description: "Unable to access microphone.",
        variant: "destructive",
      })
    }
  }

  const stopRecording = () => {
    mediaRecorder?.stop()
  }

  const handleRecordingStop = useCallback(async () => {
    setIsRecording(false)
    const blob = new Blob(audioChunks.current, { type: "audio/webm" })
    audioChunks.current = []

    const formData = new FormData()
    formData.append("file", blob, "recording.webm")

    setIsTranscribing(true)
    try {
      const res = await fetch("/api/openai/transcribe", {
        method: "POST",
        body: formData,
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error || "Failed to transcribe")

      const text: string = data.text || ""
      if (text) {
        setDescription((prev) => (prev.trim() ? `${prev}\n${text}` : text))
      }
    } catch (err) {
      toast({ description: String(err), variant: "destructive" })
    } finally {
      setIsTranscribing(false)
    }
  }, [])

  return (
    <form
      onSubmit={handleSubmit}
      className="mb-6 grid gap-4 border-b border-muted pb-6"
    >
      <div className="grid gap-2">
        <Textarea
          id="description"
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          placeholder="Describe a task or use the microphone to speak..."
          required
          disabled={isSubmitting}
          rows={3}
        />
      </div>
      <div className="flex flex-wrap items-center gap-x-4 gap-y-2">
        <Button type="submit" disabled={isSubmitting}>
          {generatingTitle ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" /> Generating
              title...
            </>
          ) : loading ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" /> Creating...
            </>
          ) : (
            "Create Task"
          )}
        </Button>

        <Button
          type="button"
          variant="secondary"
          onClick={isRecording ? stopRecording : startRecording}
          disabled={isSubmitting || isTranscribing}
          className={isRecording ? "animate-pulse" : ""}
          size={isRecording ? undefined : "icon"}
        >
          {isTranscribing ? (
            <Loader2 className="h-4 w-4 animate-spin" />
          ) : isRecording ? (
            <>
              <Mic className="mr-2 h-4 w-4" /> Listening...
            </>
          ) : (
            <Mic className="h-4 w-4" />
          )}
        </Button>
      </div>
    </form>
  )
}
