name: Build and Push Worker Docker Image

on:
  # push:
  # branches:
  # - main
  # Allow manual runs on any branch
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build and push workflow-workers image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for cross-arch builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute date-time tag (UTC)
        run: echo "DATE_TAG=$(date -u '+%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Define image name
        id: vars
        run: echo "IMAGE=ghcr.io/${{ github.repository_owner }}/workflow-workers" >> $GITHUB_ENV

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=sha,format=short
            type=raw,value=latest
            type=raw,value=${{ env.DATE_TAG }}

      - name: Build and push (cache enabled)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/workers/workflow-workers/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

      # Safer, targeted cleanup: only prune the Buildx cache for the builder created above.
      - name: Prune Buildx cache for this builder
        if: always()
        run: |
          docker buildx prune --builder "${{ steps.buildx.outputs.name }}" -f || true
