name: Deploy to youngandai-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Fetch latest updates
        run: git fetch origin main
        working-directory: /home/ec2-user/issue-to-pr/

      - name: Pull latest changes
        run: git pull origin main
        working-directory: /home/ec2-user/issue-to-pr/

      - name: Install dependencies
        run: npm install
        working-directory: /home/ec2-user/issue-to-pr/

      - name: Build project
        run: npm run build
        working-directory: /home/ec2-user/issue-to-pr/

      - name: Restart EC2 service
        run: sudo systemctl restart issue-to-pr.service
