name: Deploy to youngandai-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull latest image and recreate containers
        working-directory: /home/ec2-user/issue-to-pr/docker/
        run: |
          # Point docker-compose env_file to production env vars
          export ENV_FILE=../.env.production.local
          docker compose pull
          docker compose up -d --remove-orphans
