name: Deploy to youngandai-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Fetch latest updates
        run: git fetch origin main

      - name: Pull latest changes
        run: git pull origin main

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Copy files to application directory
        run: |
          rsync -av --delete ${{ github.workspace }}/ /home/ec2-user/issue-to-pr/

      - name: Restart EC2 service
        run: sudo systemctl restart issue-to-pr.service
